[package]
name = "xp_docker"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.14"
tokio = { version = "1.28", features = ["full"] }
futures-util = "0.3"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.139"
tar = "0.4.44"
hyper = "1.6.0"

